import os
import re
import shutil

def process_files_in_folder(input_folder, output_folder):
    # Iterate over all files in the input folder
    for filename in os.listdir(input_folder):
        if filename.endswith(".smt2"):
            input_file_path = os.path.join(input_folder, filename)
            output_subfolder = os.path.join(output_folder, filename.replace(".smt2", ""))
            
            # Create the output subfolder
            if not os.path.exists(output_subfolder):
                os.makedirs(output_subfolder)
            
            # Copy the original file to the output subfolder
            shutil.copy(input_file_path, os.path.join(output_subfolder, "origin.smt2"))
            
            # Process the file and generate the template and goals files
            process_smt2_file(input_file_path, output_subfolder)

def process_smt2_file(input_file_path, output_subfolder):
    template_lines = []
    goals = []
    datatypes = []
    conjectures = []
    decfuns = []

    # Regexes matching lines of the form (assert (not ...))
    assert_not_pattern = re.compile(r'\(assert \(not .*\)\)')
    assert_pattern = re.compile(r'\(assert \(.*\)\)')
    datatype_pattern = re.compile(r'\(declare-datatypes \(.*\)\)')
    decfun_pattern = re.compile(r'\(declare-fun .*\)')
    deffun_pattern = re.compile(r'\(define-fun .*\)')
    
    with open(input_file_path, 'r') as infile:
        for line in infile:
            # If the line matches (assert (not ...)), add it to the goals list
            if assert_not_pattern.search(line):
                goals.append(line.strip())

            if assert_pattern.search(line):
                if not assert_not_pattern.search(line):
                    conjectures.append(line.strip())

            if datatype_pattern.search(line):
                datatypes.append(line.strip())  
            
            if decfun_pattern.search(line) or deffun_pattern.search(line):
                decfuns.append(line.strip())

            elif "(check-sat)" not in line and "(exit)" not in line:
                template_lines.append(line)
    
    # If no goals were identified, print a message
    if not goals:
        print(f"No goals found in file: {input_file_path}")
    
    generated_lemms_path = os.path.join(output_subfolder, "generated_lemmas.smt2")
    with open(generated_lemms_path, 'w') as generated_lemms:
        generated_lemms.write(";-------------- generated lemmas ---------------\n")

    # Generate the template file
    template_file_path = os.path.join(output_subfolder, "template.smt2")
    with open(template_file_path, 'w') as template_file:
        template_file.write(";-------------- datatypes ---------------\n")
        # for line in template_lines:
        #     template_file.write(line)
        # Insert {invalid_lemmas}, {new_lemmas}, {goals} placeholders before (check-sat)
        for datatype in datatypes:
            template_file.write(datatype + '\n')
        template_file.write(";-------------- End of datatypes ---------------\n")
        template_file.write("\n")
        
        template_file.write(";-------------- conjectures ---------------\n")
        for conjecture in conjectures:
            template_file.write(conjecture + '\n')
        template_file.write(";-------------- End of conjectures ---------------\n")
        
        template_file.write("\n")
        template_file.write(";------------------------ Goals to prove -----------------------\n")
        for goal in goals:
            template_file.write(goal + '\n')
        template_file.write(";------------------------- End of goals ------------------------\n")
        
        template_file.write(";-------------- Invalid lemmas generated by LLMs ---------------\n")
        template_file.write("{invalid_lemmas}\n")
        template_file.write(";-------------------- End of invalid lemmas --------------------\n")
        
        template_file.write(";...... new conjectures ......\n")
        template_file.write("{new_lemmas}\n")
        template_file.write(";---------------------- End of new conjectures ----------------------\n")
    
    # Generate definition files for the cvc5 API
    definitions_file_path = os.path.join(output_subfolder, "definitions.smt2")
    with open(definitions_file_path, 'w') as definitions_file:
        for datatype in datatypes:
            definitions_file.write(datatype + '\n')
        for decfun in decfuns:
            definitions_file.write(decfun + '\n')       
    
    # # Generate the goals file
    # goals_file_path = os.path.join(output_subfolder, "goals")
    # with open(goals_file_path, 'w') as goals_file:
    #     for goal in goals:
    #         goals_file.write(goal + "\n")
    
    # # Generate the new_lemmas file (empty for now)
    # new_lemmas_file_path = os.path.join(output_subfolder, "new_lemmas")
    # with open(new_lemmas_file_path, 'w') as new_lemmas_file:
    #     new_lemmas_file.write("")

    # # Generate the invalid_lemmas file (empty for now)
    # invalid_lemmas_file_path = os.path.join(output_subfolder, "invalid_lemmas")
    # with open(invalid_lemmas_file_path, 'w') as invalid_lemmas_file:
    #     invalid_lemmas_file.write("")

def synthesize_smt2_file(template_path, invalid_lemmas_path, new_lemmas_path, goals_path, output_path):
    """
    Synthesize a new smt2 file from the template file, the new_lemmas file, and the goals file.
    """
    with open(template_path, 'r') as template_file:
        template_content = template_file.read()

    with open(invalid_lemmas_path, 'r') as invalid_lemmas_file:
        invalid_lemmas_content = invalid_lemmas_file.read()
    
    with open(new_lemmas_path, 'r') as new_lemmas_file:
        new_lemmas_content = new_lemmas_file.read()
    
    with open(goals_path, 'r') as goals_file:
        goals_content = goals_file.read()
    
    # Replace the placeholders in the template
    synthesized_content = template_content.replace("{new_lemmas}", new_lemmas_content)
    synthesized_content = synthesized_content.replace("{invalid_lemmas}", invalid_lemmas_content)
    synthesized_content = synthesized_content.replace("{goals}", goals_content)
    
    # Write the synthesized content to the output file
    with open(output_path, 'w') as output_file:
        output_file.write(synthesized_content)

if __name__ == "__main__":
    input_folder = "testcases/nosg"  # path to the input folder
    output_folder = "fwzProcessed"  # path to the output folder
    
    if not os.path.exists(output_folder):
        os.makedirs(output_folder)
    
    process_files_in_folder(input_folder, output_folder)
    
    # # Example: how to synthesize a new smt2 file using the template file
    # example_subfolder = os.path.join(output_folder, "nichomachus-goal2")
    # if os.path.exists(example_subfolder):
    #     template_path = os.path.join(example_subfolder, "template")
    #     new_lemmas_path = os.path.join(example_subfolder, "new_lemmas")
    #     invalid_lemmas_path = os.path.join(example_subfolder, "invalid_lemmas")
    #     goals_path = os.path.join(example_subfolder, "goals")
    #     synthesized_smt2_path = os.path.join(example_subfolder, "synthesized.smt2")
        
    #     synthesize_smt2_file(template_path, invalid_lemmas_path, new_lemmas_path, goals_path, synthesized_smt2_path)
    #     print(f"Synthesized SMT2 file created at: {synthesized_smt2_path}")